### ISSUE TITLE
maximum call stack size exceeded

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#52] opened 2017-07-13 07:11 UTC
After installing harvard.cs50.droplet under `~/.c9/plugins/`, entering SDK and debug modes (by adding `sdk=1&debug=2` to the URL), and enabling harvard.cs50.droplet from *CS50 IDE > Preferences > PLUGIN EXPLORER > Locally Installed Plugins*, to test harvard.cs50.droplet:into-menu, I get a maximum call stack size exceeded error per the log below, once the plugin is loaded:

```
blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1 Uncaught RangeError: Maximum call stack size exceeded
e @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
(anonymous) @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
d.108.../antlr/CDroppabilityGraph.json @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:28
e @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
(anonymous) @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
d.110.../antlr.coffee @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:28
e @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
(anonymous) @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
d.117../languages/c.coffee @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:31
e @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
(anonymous) @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
d.120../modes.coffee @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:32
e @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
a @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
(anonymous) @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
(anonymous) @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
(anonymous) @ blob:https://ide.c9.io/ca7b28bd-bc19-45d1-9d51-0aed739fbdc3:1
```

**Comment by dabbler0** [comment] 2017-07-13 17:27
This is weird; I can't reproduce it (installed `harvard.cs50.droplet` under `.c9/plugins` and entered SDK and debug mode, then enabled the plugin as described, and everything seems to work as expected). Maybe delete and re-clone the repository?

The shown error stack doesn't seem to have any suspicious repeated frames in it; maybe somehow the maximum stack size got really small? Is there any way that could happen?

**Comment by kzidane** [comment] 2017-07-13 17:35
Did you switch to `into-menu`? Just deleted and re-cloned, and still getting the same error:

```
~/.c9/plugins/ $ pwd
/home/ubuntu/.c9/plugins
~/.c9/plugins/ $ git clone -b into-menu https://github.com/cs50/harvard.cs50.droplet.git
Cloning into 'harvard.cs50.droplet'...
remote: Counting objects: 792, done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 792 (delta 35), reused 50 (delta 25), pack-reused 731
Receiving objects: 100% (792/792), 3.85 MiB | 1.49 MiB/s, done.
Resolving deltas: 100% (409/409), done.
```
The error disappears when droplet is disabled. Can share the workspace with you, if you'd like to take a closer look? If so, mind commenting with (or sending me) your Cloud9 username, please?

**Comment by dabbler0** [comment] 2017-07-13 17:40
Sure; I'm `dabbler`.

**Comment by kzidane** [comment] 2017-07-13 17:40
Just shared!

**Comment by dabbler0** [comment] 2017-07-13 17:44
It also works for me in your workspace:
![2017-07-13-134336_1366x768_scrot](https://user-images.githubusercontent.com/682790/28179856-4b5f42e6-67d1-11e7-8628-57f6d91abc32.png)

I also tried it in Firefox 52.0.1 and it seems to work; my Chromium version is 58.0.3029.81.

**Comment by kzidane** [comment] 2017-07-13 17:54
Interesting! 
![stack](https://user-images.githubusercontent.com/7230211/28180087-0ec58614-67d2-11e7-8046-382965ecc108.png)

Running Chrome 59.0.3071.115 on Ubuntu 14.04. Getting a different error on Firefox 54.0:

![firefox](https://user-images.githubusercontent.com/7230211/28180290-a9eae2a6-67d2-11e7-8a8d-a0fbb0f42924.png)

```
TypeError: correctItemDisplay is not a function[Learn More]  droplet.js:631:33
	attachToAce/< https://vfs-gce-usw-129-2.c9.io/vfs/5099728/9cinTetrcUZS4EeG/home/.c9/plugins/harvard.cs50.droplet/droplet.js:631:33
	EventEmitter._signal https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:5569:36
	this.setSession https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:12918:36
	Ace/< https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:39129:74
	EventEmitter.prototype.emit https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:209:183
	bound  self-hosted:915:17
	unloadDocument https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:40831:17
	loadDocument/< https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:40839:28
	EventEmitter.prototype.emit https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:209:183
	unload https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:43461:11
	createTab/< https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:40162:47
	EventEmitter.prototype.emit https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:209:183
	bound  self-hosted:915:17
	Tab/< https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:40411:57
	EventEmitter.prototype.emit https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:206:15
	unload https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:43461:11
	closeNow/< https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:39780:73
	wrapped https://static.c9.io/nc-3.1.3677-4a6ec6d8/config/workspace-cs50.js:9750:31
```

**Comment by dabbler0** [comment] 2017-07-13 18:05
I'll update my browsers and see if this causes the error. It's also possible it's caused by some timing-dependent race condition; it seems likely that least the second error is, as the procedure by which I put the button into the list between "Auto-Select" and "Plain Text" is pretty fragile.

**Comment by dabbler0** [comment] 2017-07-13 18:57
Weird! Updating 59.0.3071.115 does cause the error for me. I'll try to figure out what it is.

**Comment by dabbler0** [comment] 2017-07-13 19:19
I was able to fix the Firefox issue, which was a race condition problem. I still don't know what's going on with the stack call size in Chrome. It seems to be happening during Browserify's module dependency resolution.

**Comment by dabbler0** [comment] 2017-07-13 19:28
I'll try a version without minification to see if I can diagnose it.

**Comment by dabbler0** [comment] 2017-07-13 19:48
Hmm, it seems to actually be in the ANTLR parser for some reason.

Is there an older commit which does work? Could we figure out what the changes are?

**Comment by kzidane** [comment] 2017-07-13 19:57
@dabbler0 I guess `master` doesn't have this issue.

**Comment by dabbler0** [comment] 2017-07-13 20:32
Alright. `master` works, but `into-menu` doesn't, and the problem seems to be in loading the ANTLR parser, so I think that my fix for #50 is what broke it. I'm going to see if I can figure out why.

**Comment by dmalan** [comment] 2017-08-22 04:41
Any luck, @dabbler0?

**Comment by crossroads1112** [comment] 2018-02-27 18:40
From what I understand from @kzidane, the feature being developed in `into-menu` is no longer a priority? If this is the case, I would propose closing this issue since this does not affect master.

**Comment by kzidane** [comment] 2018-02-27 18:44
That's assuming the feature was injecting toggle into syntax menu that was on lower-right corner of ace. We've since decided it was going to be a togglable puzzle piece icon (which it is now) and we got rid of the menu for simplicity.

**Comment by crossroads1112** [comment] 2018-02-28 01:14
Looking at that branch, it isn't really clear what the differences between it and master are (save being 43 commits behind master). Since this bug does not seem to be an issue on master, I'm closing for now. If it pops up again, we can reopen.

**Closed** 2018-02-28 01:14 UTC
Labels: bug
