### ISSUE TITLE
Newline error

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#12] opened 2016-08-25 18:41 UTC
While testing droplet after the latest fixes, detected a couple of bugs. To reproduce the first one:
1. open new .c file
2. switch to "Blocks" view
3. hit "Enter"

You should get an error caused by droplet-full.js:23, as reported

> Uncaught TypeError: Cannot read property 'indentContext' of null

To reproduce the second one:
1. repeat steps 1 & 2 above
2. insert a block (e.g., a function)
3. get the cursor to blink inside the block and hit "Enter"
4. insert another block

I got different errors depending on the block inserted at step 4.

Screencast:  [droplet-newline-errors.zip](https://github.com/cs50/harvard.cs50.droplet/files/437805/droplet-newline-errors.zip)

**Comment by dabbler0** [comment] 2016-08-26 06:15
I've identified the cause of this bug, but I do not have time to fix it in a clean systemic way this week. I have committed a hotfix hack which solves some cases properly, and added an abort pathway that the cursor back at the top of the document when it gets too confused instead of breaking the editor. This hack eliminates all related breaking conditions.

Later in the fall I will try to clean this up to get the desired behavior in all cases.

**Comment by dabbler0** [comment] 2016-11-19 00:27
Update: this is now tested in cs50-unstable, so can be pushed through whenever. I'm going to wait until the other two cs50-unstable features are tested and then push the whole thing through at once.

**Comment by dabbler0** [comment] 2016-11-19 01:42
Merged!

**Closed by dabbler0** 2016-11-19 01:42 UTC
Labels: bug

**Comment by dmalan** [comment] 2016-11-19 23:18
Thanks!
