### ISSUE TITLE
__0_droplet__ shows in place of removed function parameter

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#31] opened 2017-05-31 19:18 UTC
![remove-param](https://cloud.githubusercontent.com/assets/7230211/26649547/aa5f0378-4646-11e7-9247-fa719c5a47c4.gif)

**Comment by dabbler0** [comment] 2017-06-01 02:15
Is the expected behavior to have no parameters there, instead? This is currently intentional to preserve the empty socket. Without the placeholder, when you flip back to blocks, you'll see no empty socket but just the two arrow buttons. This is much more obviously appropriate when you have multiple parameters: if you have a function with three parameters and remove all of the blocks, leaving empty sockets that look like `___, ___, ___`, then flip to text, you definitely want to preserve the information that you have three parameters as opposed to 0.

I don't think it would be hard to special-case the case where there's a single empty socket in a list, but it cause it to have different behavior from when there are any other number of sockets in the list.

Another option is to change what the placeholder is (I chose `__0_droplet__` simply because it would be very unlikely to be a real variable name) so that it is less shocking to users when it appears. That's very easy to do, if you have any ideas for a better placeholder name.

**Comment by dmalan** [comment] 2017-06-01 06:34
Feels best to have the placeholder be just `" "` if possible, else I'd just remove the arg altogether and expect the user to click the right-arrow to add an arg back.

**Comment by dabbler0** [comment] 2017-06-01 13:07
The placeholder would have to be a valid C identifier, so possibly `_` or `__` could work. If that's still too visible I can do the special-casing thing instead.

**Comment by dmalan** [comment] 2017-06-01 15:24
Hm, feels messy to add invalid syntax to otherwise valid C code. Though what happens if you convert a `for` loop's block to C code before you've inputted the semicolon-separated initialization, condition, update?

**Comment by dabbler0** [comment] 2017-06-01 22:09
The same; you'd get a `__0_droplet__` placeholder. The syntax is still valid; it uses `__0_droplet__` as if it were a variable name. If "0_droplet" is confusing, we could switch this to `__`.

With a `for` loop, we definitely need some placeholder; otherwise we can't parse back into blocks after toggling.

**Comment by dmalan** [comment] 2017-06-01 22:59
Okay, need it be double underscore, or would `_` suffice for placeholders?

**Comment by dabbler0** [comment] 2017-06-02 01:57
`_` should suffice for placeholders, unless you expect any student to use `_` as a real variable name (in which case if they switched to blocks it would be replaced by an empty socket).

**Comment by dmalan** [comment] 2017-06-02 01:59
Let's keep it simple with `_` for now, just one underscore!

**Comment by dabbler0** [comment] 2017-06-16 07:00
As of now it should be one underscore; closing.

**Closed by dabbler0** 2017-06-16 07:00 UTC
Labels: bug
