### ISSUE TITLE
changes value of all ace documents

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#55] opened 2017-07-16 14:00 UTC
Editing one document changes values of documents in tabs open in all other panes.

> Don't know if this happened previously (I just updated to v101)
> 
> If two individual files are open and the "Split pane in two columns (or rows)" command is invoked, a change or edit on one file causes that files contents to be replicated and replaces the contents of the other file.
> 
> This issue seems applicable only to the CS50 IDE, I tried to replicate the problem in my personal C9 workspace and the split pane works as expected.

https://github.com/cs50/libcs50/issues/96

![](https://slack-imgs.com/?c=1&url=http%3A%2F%2Fg.recordit.co%2FC3fz3bExDe.gif)

**Comment by dlloyd09** [comment] 2017-07-21 21:33
@dabbler0 has a local fix to be deployed!

**Comment by dabbler0** [comment] 2017-07-24 03:46
Should be fixed now.

**Comment by dmalan** [comment] 2017-07-24 03:50
Thanks!

**Comment by MadDogDean** [comment] 2017-07-27 03:33
Nice work guys, Thanks!

**Comment by kzidane** [comment] 2017-07-31 19:34
![content](https://user-images.githubusercontent.com/7230211/28794838-c4c7d7b4-7605-11e7-984c-28a0af1bfbc6.gif)

**Comment by MadDogDean** [comment] 2017-08-01 00:33
@kzidane 
Is this broken in v103? v102 seems to work fine and as expected. Should we wait with v103 until v104?

**Comment by kzidane** [comment] 2017-08-01 04:12
This is actually not deployed atm, @MadDogDean!

**Comment by MadDogDean** [comment] 2017-08-01 04:24
No trouble. I am subscribed to the issue, so I followed the notification and wondered what you were showing.... 
Cheers

**Comment by dabbler0** [comment] 2017-08-09 18:05
@kzidane does this issue need additional attention? If so, what is happening?

**Comment by kzidane** [comment] 2017-08-09 22:02
@dabbler0 I think this hasn't been fixed per https://github.com/cs50/harvard.cs50.droplet/issues/55#issuecomment-319172775!

**Comment by MadDogDean** [comment] 2017-08-09 22:27
@kzidane @dabbler0 As far as I can tell, this works fine. My original concern has been resolved.
Cheers,

**Comment by kzidane** [comment] 2017-08-23 17:07
Afraid this still hasn't been fixed :slightly_frowning_face: 

![content](https://user-images.githubusercontent.com/7230211/29628625-0d9dda78-8804-11e7-8793-59f27a7c6e6f.gif)

**Comment by MadDogDean** [comment] 2017-08-24 01:48
@kzidane  Running this on Win7 under Firefox 51.0.1, I am not seeing what you are. CS50 IDE v110.

**Comment by dabbler0** [comment] 2017-08-30 05:19
@kzidane I also cannot reproduce this; running online (with plugin loaded with debug mode) on Chrome 60.0.3312.101 on Windows, and also cannot reproduce running Chrome 59.0.3071.115 on Linux.

**Comment by dabbler0** [comment] 2017-08-31 20:56
Should really be fixed now; entirely removed the buggy code path.

**Closed by dabbler0** 2017-08-31 20:56 UTC
Labels: bug, high priority
